### ISSUE TITLE
postInstallation errors in latest version

### ISSUE THREAD

**Issue by prydonius** [bitnami/bitnami-docker-phpbb#32] opened 2017-01-26 00:29 UTC
When I bring up the latest version using the Compose file I'm seeing a postInstallation error. I'm also getting a different postInstallation error when testing the chart update.

```
$ docker-compose up -d
$ docker-compose logs -f phpbb
Attaching to bitnamidockerphpbb_phpbb_1
phpbb_1    | nami    INFO  Initializing apache
phpbb_1    | apache  INFO  ==> Patching httpoxy...
phpbb_1    | nami    INFO  apache successfully initialized
phpbb_1    | nami    INFO  Initializing php
phpbb_1    | nami    INFO  php successfully initialized
phpbb_1    | nami    INFO  Initializing phpbb
phpbb_1    | mysqlCo INFO  Trying to connect to MySQL server
phpbb_1    | mysqlCo INFO  Found MySQL server listening at mariadb:3306
phpbb_1    | mysqlCo INFO  MySQL server listening and working at mariadb:3306
phpbb_1    | phpbb   INFO  Passing wizard, please be patient
phpbb_1    | phpbb   INFO  Wizard Installation completed
phpbb_1    | Error executing 'postInstallation': PHP Fatal error:  SQL ERROR [ mysqli ]<br /><br />Duplicate entry 'assets_version' for key 'PRIMARY' [1062]<br /><br />An SQL error occurred while fetching this page. Please contact the Board Administrator if this problem persists. in /opt/bitnami/phpbb/phpbb/db/driver/driver.php on line 999
phpbb_1    |
```

In the Kubernetes chart (https://github.com/kubernetes/charts/pull/491) I'm seeing:
```
$ kubectl logs -n pr-491-0 -f phpbb-0-phpbb-2192143679-h88hj
nami    INFO  Initializing apache
apache  INFO  ==> Patching httpoxy...
nami    INFO  apache successfully initialized
nami    INFO  Initializing php
nami    INFO  php successfully initialized
nami    INFO  Initializing phpbb
mysqlCo INFO  Trying to connect to MySQL server
mysqlCo INFO  Found MySQL server listening at phpbb-0-mariadb:3306
mysqlCo INFO  MySQL server listening and working at phpbb-0-mariadb:3306
phpbb   INFO  Passing wizard, please be patient
Error executing 'postInstallation': Cannot read property 'substring' of undefined
No INPUT matching 'admin_name'
```

**Comment by migmartri** [comment] 2017-01-26 00:36
I can reproduce the error in my Ubuntu box following the same procedure that @prydonius outlined.

**Comment by sameersbn** [comment] 2017-01-26 05:10
I can reproduce the issue with `docker-compose`, I see a different error though. 

```
Attaching to phpbb_phpbb_1
phpbb_1    | nami    INFO  Initializing apache
phpbb_1    | apache  INFO  ==> Patching httpoxy...
phpbb_1    | nami    INFO  apache successfully initialized
phpbb_1    | nami    INFO  Initializing php
phpbb_1    | nami    INFO  php successfully initialized
phpbb_1    | nami    INFO  Initializing phpbb
phpbb_1    | mysqlCo INFO  Trying to connect to MySQL server
phpbb_1    | mysqlCo INFO  Found MySQL server listening at mariadb:3306
phpbb_1    | mysqlCo INFO  MySQL server listening and working at mariadb:3306
phpbb_1    | phpbb   INFO  Passing wizard, please be patient
phpbb_1    | Error executing 'postInstallation': Cannot read property 'substring' of undefined
phpbb_1    | No INPUT matching 'admin_name'
```

**Comment by prydonius** [comment] 2017-01-26 20:12
@sameersbn I got that particular error in the chart.

**Comment by migmartri** [comment] 2017-01-26 20:36
I have run it again using the compose file in this repository and I believe that the error below is due to the fact that there was an existing named volume in the system. 

```
phpbb_1    | Error executing 'postInstallation': PHP Fatal error:  SQL ERROR [ mysqli ]<br /><br />Duplicate entry 'assets_version' for key 'PRIMARY' [1062]<br /><br />An SQL error occurred while fetching this page. Please contact the Board Administrator if this problem persists. in /opt/bitnami/phpbb/phpbb/db/driver/driver.php on line 999
phpbb_1    |
```

But even if I ensure that I have a clean environment, installation fails with no output

````
mariadb_1  | 2017-01-26 20:31:51 139985546107648 [Note] InnoDB: Online DDL : End of reading clustered index of the table and create temporary files
mariadb_1  | 2017-01-26 20:31:51 139985546107648 [Note] InnoDB: Online DDL : Start applying row log
mariadb_1  | 2017-01-26 20:31:51 139985546107648 [Note] InnoDB: Online DDL : End of applying row log
mariadb_1  | 2017-01-26 20:31:51 139985546107648 [Note] InnoDB: Online DDL : Completed
phpbb_1    | Error executing 'postInstallation': Program exited with exit code 1

```

Which can not be retried since I get other SQL initialization errors

```
phpbb_1    | Error executing 'postInstallation': PHP Fatal error:  SQL ERROR [ mysqli ]<br /><br />Unknown column 'user_pass_convert' in 'where clause' [1054]<br /><br />An SQL error occurred while fetching this page. Please contact the <a href="mailto:contact@yourdomain.tld">Board Administrator</a> if this problem persists. in /opt/bitnami/phpbb/phpbb/db/driver/driver.php on line 999
```

**Comment by prydonius** [comment] 2017-01-26 21:39
FYI, In the meantime, I've rolled back the `latest` tag to `3.1.10-r0`.

**Comment by andresbono** [comment] 2017-05-23 10:24
[3.2.0-r4](https://github.com/bitnami/bitnami-docker-phpbb/releases/tag/3.2.0-r4) release fixes this issue. Closing it.

**Closed** 2017-05-23 10:24 UTC
